### ISSUE TITLE
404's for project build via sbt

### ISSUE THREAD

**Issue by sguldanbird** [gnostix/freeswitch-monitoring#2]
./sbt
Detected sbt version 0.13.8
Starting sbt: invoke with -help for other options
Downloading sbt launcher 0.13.8:
  From  http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar
    To  ./.lib/0.13.8/sbt-launch.jar
Download failed. Obtain the jar manually and place it at ./.lib/0.13.8/sbt-launch.jar
root@fpbx-01:~/freeswitch-monitoring# wget http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar
--2016-08-23 22:26:12--  http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar
Resolving typesafe.artifactoryonline.com (typesafe.artifactoryonline.com)... 52.23.0.113, 107.23.26.63
Connecting to typesafe.artifactoryonline.com (typesafe.artifactoryonline.com)|52.23.0.113|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-08-23 22:26:12 ERROR 404: Not Found.

**Comment by gnostix** [comment]
from my laptop I can run sbt successfully and build/run the project. Maybe is something related with typesafe servers or your network connectivity.
