### ISSUE TITLE
war file unavailable

### ISSUE THREAD

**Issue by sguldanbird** [gnostix/freeswitch-monitoring#3]
fs-moni.cloudapp.net not resolving...! Maybe Azure is down? ;-)

wget http://fs-moni.cloudapp.net/freeswitchop_2.11-0.1.0-SNAPSHOT.war
--2016-08-23 22:35:59--  http://fs-moni.cloudapp.net/freeswitchop_2.11-0.1.0-SNAPSHOT.war
Resolving fs-moni.cloudapp.net (fs-moni.cloudapp.net)... **0.0.0.0**
Connecting to fs-moni.cloudapp.net (fs-moni.cloudapp.net)|**0.0.0.0**|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-08-23 22:35:59 ERROR 404: Not Found.

**Comment by gnostix** [comment]
Hi there,
The server was down and that is why you had issues downloading the war..
please try again
