### ISSUE TITLE
Getting error during installation

### ISSUE THREAD

**Issue by vijayaa** [gnostix/freeswitch-monitoring#4]
When i run ./sbt the following error is shown

[info] Set current project to FreeswitchOP (in build file:/home/freeswitch/freeswitch-monitoring/)

Can you please tell me what should be changed

**Comment by gnostix** [comment]
you have to be inside the project when you run sbt. Everything should be straightforward from there.
you can also install your own sbt to your OS and build from there the project the same way as before just remove the "./" before sbt

**Comment by gnostix** [comment]
you can also download the war file.

**Comment by vijayaa** [comment]
war file  (http://fs-moni.cloudapp.net/freeswitchop_2.11-0.1.0-SNAPSHOT.war ) not found

**Comment by gnostix** [comment]
now it's ok. please try again

**Comment by vijayaa** [comment]
OK thank you.Can i deploy this under tomcat

**Comment by gnostix** [comment]
yes with Tomcat works but with Jetty is tested well and it works good.
