### ISSUE TITLE
Default login?

### ISSUE THREAD

**Issue by watsonlabs** [gnostix/freeswitch-monitoring#5]
What's the default login if using the .WAR file?

**Comment by gnostix** [comment]
admin / admin

You can find it also in the documentation

**Comment by watsonlabs** [comment]
Getting a 404. 
http://screenshot.watsonnetworks.com/0k0p381f0002

**Comment by gnostix** [comment]
You need to run the war as the root app. So it runs in ip:port/
Check the manual in git hub front page and you will see how to do that. If still you have a problem then I will build for you a new war file without authentication.
